apiVersion: v1
kind: Pod
metadata:
  name: jupyter-cloud-test
  namespace: test
spec:
  nodeSelector:
    topology.kubernetes.io/zone: verda
  tolerations:
    - key: "node-role.kubernetes.io/cloud"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  containers:
  - name: jupyter
    image: jupyter/scipy-notebook:latest
    ports:
    - containerPort: 8888
    resources:
      requests:
        cpu: "2000m"
        memory: "8Gi"
      limits:
        cpu: "2000m"
        memory: "8Gi"
