apiVersion: v1
kind: Pod
metadata:
  name: jupyter-cloud-gpu-test
  namespace: default
spec:
  nodeSelector:
    topology.kubernetes.io/zone: verda
  tolerations:
    - key: "node-role.kubernetes.io/cloud"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  volumes:
  - name: tmp-volume
    emptyDir:
      sizeLimit: 20Gi

  containers:
  - name: jupyter
    image: quay.io/jupyter/tensorflow-notebook:cuda-latest
    ports:
    - containerPort: 8888

    volumeMounts:
    - mountPath: /tmp
      name: tmp-volume

    resources:
      requests:
        cpu: "2000m"
        memory: "4Gi"

      limits:
        cpu: "2000m"
        memory: "4Gi"
