apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: route-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: route-manager
  template:
    metadata:
      labels:
        app: route-manager
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/role
                    operator: NotIn
                    values:
                      - cloud-worker
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      initContainers:
        - name: add-route
          image: busybox:1.36
          env:
            - name: WG_GATEWAY_ADDR
              valueFrom:
                configMapKeyRef:
                  name: verda-provider-config
                  key: WG_GATEWAY_ADDR
          command:
            - /bin/sh
            - -c
            - |
              ip route replace 10.200.0.0/16 via "${WG_GATEWAY_ADDR}"
          securityContext:
            privileged: true
      containers:
        - name: pause
          image: busybox:1.36
          command: ["/bin/sh", "-c", "sleep infinity"]
